output "hostname" {
  description = "The hostname of the machine hosting the Connector"
  value       = twingate_connector.this.hostname
}

output "id" {
  description = "Autogenerated ID of the Connector, encoded in base64"
  value       = twingate_connector.this.id
}

output "private_ips" {
  description = "The Connector's private IP addresses"
  value       = twingate_connector.this.private_ips
}

output "public_ip" {
  description = "The Connector's public IP address"
  value       = twingate_connector.this.public_ip
}

output "state" {
  description = "The Connector's state"
  value       = twingate_connector.this.state
}

output "version" {
  description = "The Connector's version"
  value       = twingate_connector.this.version
}
