output "hostname" {
  description = "The hostname of the machine hosting the Connector"
  value       = module.twingate_connector.hostname
}

output "id" {
  description = "Autogenerated ID of the Connector, encoded in base64"
  value       = module.twingate_connector.id
}

output "private_ips" {
  description = "The Connector's private IP addresses"
  value       = module.twingate_connector.private_ips
}

output "public_ip" {
  description = "The Connector's public IP address"
  value       = module.twingate_connector.public_ip
}

output "state" {
  description = "The Connector's state"
  value       = module.twingate_connector.state
}

output "version" {
  description = "The Connector's version"
  value       = module.twingate_connector.version
}
